openapi: "3.0.0"

servers:
    - url: http://localhost:8080
      description: Development server
      variables:
        email:
            default: admin@bfriend.ch
            enum:
                - admin@bfriend.ch
                - moderator@bfriend.ch
                - passive_user@bfriend.ch
                - active_user@bfriend.ch
                - deactivated_user@bfriend.ch
        password:
            default: '123456'
        role:
            default: admin
            enum:
                - admin
                - moderator
                - passive_user
                - active_user
                - deactivated_user

info:
    version: "1.0.0"
    title: "bFriend API"
    description: Find people with the same hobbies and interests

paths:
    /:
        get:
            summary: returns a "Hello World" String
            responses:
                "200":
                    description: the "Hello World" String
                    content:
                        text/plain:
                            examples:
                                valid_hello_world:
                                    value:
                                        "Hello World!"
    /api/auth/logout:
        post:
            summary: logs out a logged in user
            
            responses:
                "200":
                    description: user has been successfully logged out
                    content:
                        application/json:
                            examples:
                                valid_logout:
                                    value:
                                        "You have been logged out successfully!"
    /api/auth/login:
        post:
            summary: logs in a user, if password and email is correct
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                email:
                                    description: the email of the user that wants to log in
                                    type: string
                                    format: email
                                password:
                                    description: the password of the user that wants to log in
                                    type: string
                                    format: password
                            required:
                                - email
                                - password
                        examples:
                            login_as_admin:
                                summary: logs in as admin
                                value:
                                    email: admin@bfriend.ch
                                    password: '123456'
                            login_as_passive_user:
                                summary: logs in as passive user
                                value:
                                    email: passive_user@bfriend.ch
                                    password: '123456'

            responses:
                "200":
                    description: credentials are correct, user is logged in
                    content:
                        application/json:
                            examples:
                                successful_login:
                                    value:
                                        {
                                            "roles": [
                                                "ADMIN"
                                            ],
                                            "id": 1,
                                            "email": "admin"
                                        }
                "401":
                    description: wrong email/password
                    content:
                        text/plain:
                            examples:
                                failed_login:
                                    value:
                                        ""
                "400":
                    description: wrong formatting (e.g. password missing)
                    content:
                        application/json:
                            examples:
                                failed_login:
                                    value:
                                        {
                                            "message": "Wrong formatting!"
                                        }
    /api/auth/register:
        post:
            summary: registers a user
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                email:
                                    description: the email of the user that wants to log in
                                    type: string
                                    format: email
                                firstname:
                                    description: the firstname of the user that wants to log in
                                    type: string
                                lastname:
                                    description: the lastname of the user that wants to log in
                                    type: string
                                hobbies:
                                    description: the hobbies of the user that wants to log in
                                    type: array
                                    items:
                                        type: string
                                location:
                                    description: the location of the user that wants to log in
                                    type: string
                                profilepicture:
                                    description: the profilepicture of the user that wants to log in
                                    type: string
                                gender:
                                    description: the gender of the user that wants to log in
                                    type: string
                                age:
                                    description: the age of the user that wants to log in
                                    type: integer
                                password:
                                    description: the password of the user that wants to log in
                                    type: string
                                    format: password
                                role:
                                    description: the roles the user will have, the parameter is required, but the array can be empty!
                                    type: array
                                    items:
                                        type: string
                            required:
                                - email
                                - firstname
                                - lastname
                                - hobbies
                                - location
                                - profilepicture
                                - gender
                                - age
                                - password
                                - role
                        examples:
                            register_as_admin:
                                summary: logs in as admin
                                value:
                                    email: admin@bfriend.ch
                                    password: '123456'
                                    role: [admin]
                                    firstname: Admin
                                    lastname: Administrator
                                    hobbies: [FOOTBALL, FISHING]
                                    location: Zürich
                                    profilepicture: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAV4AAACWBAMAAABkyf1EAAAAG1BMVEXMzMyWlpacnJyqqqrFxcWxsbGjo6O3t7e+vr6He3KoAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAEcElEQVR4nO2aTW/bRhCGh18ij1zKknMkbbf2UXITIEeyMhIfRaF1exQLA/JRclslRykO+rs7s7s0VwytNmhJtsA8gHZEcox9PTs7uysQgGEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmGYr2OWRK/ReIKI8Zt7Hb19wTcQ0uTkGh13bQupcw7gPOvdo12/5CzNtNR7xLUtNtT3CGBQ6g3InjY720pvofUec22LJPr8PhEp2OMPyI40PdwWUdronCu9yQpdPx53bQlfLKnfOVhlnDYRBXve4Ov+IZTeMgdedm0NR+xoXJeQvdJ3CvziykSukwil16W/Oe7aGjIjqc/9ib4jQlJy0uArtN4A0+cvXFvDkmUJ47sJ1Y1ATLDNVXZkNPIepQzxy1ki9fqiwbUj/I+64zxWNzyZnPuhvohJ9K70VvXBixpcu2SAHU+Xd9EKdEJDNpYP3AQr3bQSpPQ6Y6/4dl1z7ZDbArsszjA7L0g7ibB0CDcidUWVoErvIMKZh2Xs0LUzcLW6V5NfiUgNEbaYmAVL6bXl0nJRc+1S72ua/D/cTjGPlQj7eUqd7A096rYlRjdPYlhz7VIvxpVG3cemDKF+WAwLY/6XelOZKTXXzsC4xvDjjtSN6kHLhLke6PrwM8h1raf40qjrGO7H9aTEbduucjS04ZrYU/4iuS5Z2Hdt0rvCLFdmLEXcU30AGddST62o+sLcf5l6k7CP+ru4pLYqX/VFyxbm/utQbx/r22ZEbTb2f5I2kns1Y1OQR8ZyofX+TjJxj1Rz7QQVnf1QzR26Oth0ueJVYcRP6ZUPac/Rx/5M6ixO1dhSrT3Y1DpiYmx3tF4ZUdpz9LD/dSg9PXES0LB71BwcGjKROuV28lnvnv7HHJsezheBGH5+X2CfSfRbMKW+5aGs3JFjMrjGibJc0S7TJzqjHrh2hDybj9XRXNZa89Aro55XBdbW5wti2c/5WJ7jJ1RolVUn/HWpb0I58Tziup6Rx7Dm2hnbRP1GM9PW/NFmQ4PtVRVN63Wvxfmu5sowDMMwDMMwDMMwDMMwDMMwDMMwzL+CpT//F/6beoV8zb2Jmt4Qryx6lTUCsENQ75HOkhXAO3EPVgyQtKtUy3C/e+FJg17Zjnew1Xrdb9InbG4WqfUAftG+WhLwPVyfg536+MU7m4C1CMk4ZznpXZzDYI1PDL2nS1hpvc5cNd7E2sJg05Fe7/7d3Fln8Cvc3bwB616auxsKl4WPghjemHrDqyDWeu1UNW5s2btPnSQ75oOdunEwWazfwgVG0kqluYCM9OIjWOGnfA2b9G4Ha63XKpvQ8perTvTifJNhi6+WMWmi7smEZf6G8MmhlyGq+NqP8GV84TLuJr7UIQVx+bDEoEpRZIz42gs40OuN4Mv8hXzelV7KX1isH+ewTWckikyVv+CfHuqVF7I16gN0VKypX6wPsE+zFPzkinolU9UH8OMGvSpnZqKsv13p/RsMun6X5x/y2LeAr8O66lsBwzBMP/wJfyGq8pgBk6IAAAAASUVORK5CYII=
                                    gender: MALE
                                    age: 12
                            register_as_passive_user:
                                summary: logs in as passive user
                                value:
                                    email: admin@bfriend.ch
                                    password: '123456'
                                    role: []
                                    firstname: Passive
                                    lastname: User
                                    hobbies: [BASKETBALL, SNOWBOARDING]
                                    location: Zürich
                                    profilepicture: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAV4AAACWBAMAAABkyf1EAAAAG1BMVEXMzMyWlpacnJyqqqrFxcWxsbGjo6O3t7e+vr6He3KoAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAEcElEQVR4nO2aTW/bRhCGh18ij1zKknMkbbf2UXITIEeyMhIfRaF1exQLA/JRclslRykO+rs7s7s0VwytNmhJtsA8gHZEcox9PTs7uysQgGEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmEYhmGYr2OWRK/ReIKI8Zt7Hb19wTcQ0uTkGh13bQupcw7gPOvdo12/5CzNtNR7xLUtNtT3CGBQ6g3InjY720pvofUec22LJPr8PhEp2OMPyI40PdwWUdronCu9yQpdPx53bQlfLKnfOVhlnDYRBXve4Ov+IZTeMgdedm0NR+xoXJeQvdJ3CvziykSukwil16W/Oe7aGjIjqc/9ib4jQlJy0uArtN4A0+cvXFvDkmUJ47sJ1Y1ATLDNVXZkNPIepQzxy1ki9fqiwbUj/I+64zxWNzyZnPuhvohJ9K70VvXBixpcu2SAHU+Xd9EKdEJDNpYP3AQr3bQSpPQ6Y6/4dl1z7ZDbArsszjA7L0g7ibB0CDcidUWVoErvIMKZh2Xs0LUzcLW6V5NfiUgNEbaYmAVL6bXl0nJRc+1S72ua/D/cTjGPlQj7eUqd7A096rYlRjdPYlhz7VIvxpVG3cemDKF+WAwLY/6XelOZKTXXzsC4xvDjjtSN6kHLhLke6PrwM8h1raf40qjrGO7H9aTEbduucjS04ZrYU/4iuS5Z2Hdt0rvCLFdmLEXcU30AGddST62o+sLcf5l6k7CP+ru4pLYqX/VFyxbm/utQbx/r22ZEbTb2f5I2kns1Y1OQR8ZyofX+TjJxj1Rz7QQVnf1QzR26Oth0ueJVYcRP6ZUPac/Rx/5M6ixO1dhSrT3Y1DpiYmx3tF4ZUdpz9LD/dSg9PXES0LB71BwcGjKROuV28lnvnv7HHJsezheBGH5+X2CfSfRbMKW+5aGs3JFjMrjGibJc0S7TJzqjHrh2hDybj9XRXNZa89Aro55XBdbW5wti2c/5WJ7jJ1RolVUn/HWpb0I58Tziup6Rx7Dm2hnbRP1GM9PW/NFmQ4PtVRVN63Wvxfmu5sowDMMwDMMwDMMwDMMwDMMwDMMwzL+CpT//F/6beoV8zb2Jmt4Qryx6lTUCsENQ75HOkhXAO3EPVgyQtKtUy3C/e+FJg17Zjnew1Xrdb9InbG4WqfUAftG+WhLwPVyfg536+MU7m4C1CMk4ZznpXZzDYI1PDL2nS1hpvc5cNd7E2sJg05Fe7/7d3Fln8Cvc3bwB616auxsKl4WPghjemHrDqyDWeu1UNW5s2btPnSQ75oOdunEwWazfwgVG0kqluYCM9OIjWOGnfA2b9G4Ha63XKpvQ8perTvTifJNhi6+WMWmi7smEZf6G8MmhlyGq+NqP8GV84TLuJr7UIQVx+bDEoEpRZIz42gs40OuN4Mv8hXzelV7KX1isH+ewTWckikyVv+CfHuqVF7I16gN0VKypX6wPsE+zFPzkinolU9UH8OMGvSpnZqKsv13p/RsMun6X5x/y2LeAr8O66lsBwzBMP/wJfyGq8pgBk6IAAAAASUVORK5CYII=
                                    gender: FEMALE
                                    age: 19
            responses:
                "200":
                    description: user has been successfully registered
                    content:
                        application/json:
                            examples:
                                successful_register:
                                    value:
                                        {
                                            "roles": [
                                                "ADMIN"
                                            ],
                                            "id": 1,
                                            "email": "admin"
                                        }
                "409":
                    description: Username is already taken
                    content:
                        application/json:
                            examples:
                                failed_register:
                                    value:
                                        {
                                            "message": "E-Mail is already taken!"
                                        }
                "400":
                    description: wrong formatting (e.g. password missing)
                    content:
                        application/json:
                            examples:
                                failed_register:
                                    value:
                                        {
                                            "message": "Wrong formatting!"
                                        }
    /api/auth/infos:
        get:
            summary: returns user infos, if logged in
            responses:
                "200":
                    description: user has been successfully registered
                    content:
                        application/json:
                            examples:
                                logged_in:
                                    value:
                                        {
                                            "roles": [
                                                "ADMIN"
                                            ],
                                            "id": 1,
                                            "email": "admin"
                                        }
    /api/hobby/all:
        get:
            summary: Gets a list of all hobbies
            responses:
                "200":
                    description: hobbies have been successfully returned
                    content:
                            application/json:
                                examples:
                                    successful_hobby_return:
                                        value:
                                            {
                                                [
                                                    "Football",
                                                    "Basketball",
                                                    "Handball",
                                                    "Volleyball",
                                                    "Tennis",
                                                    "Swimming",
                                                    "Running",
                                                    "Cycling",
                                                    "Skiing",
                                                    "Snowboarding",
                                                    "Skating",
                                                    "Fishing"
                                                ]
                                            }


components:
    securitySchemes:
        ApiKey:
            type: apiKey
            in: header
            name: X-Api-Key
security:
    - ApiKey: []
